image:
  repository: timmi6790/netcup-offer-bot
  tag: latest
  pullPolicy: IfNotPresent

env:
  # Optional sentry url
  sentryDns: ""
  # Discord webhook url
  webHook: ""
  # Check interval in seconds
  checkInterval: 180
  # Optional log level
  logLevel: info

persistence:
  data:
    accessMode: ReadWriteOnce
    size: 10Mi

metrics:
  enabled: false
  port: 9184
  serviceMonitor:
    interval: 1m
    scrapeTimeout: 30s

resources:
  limits:
    memory: 10Mi
  requests:
    memory: 5Mi