[package]
name = "netcup-offer-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
thiserror = "1.0"
sentry = { version = "0.29.3", features = ["anyhow", "debug-images", "log", "reqwest"] }
log = "0.4.17"
fern = "0.6.1"
chrono = "0.4.23"
webhook = "2.1.2"
rss = { version = "2.0.0", features = ["validation"] }
reqwest = { version = "0.11" }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.11"
strum = "0.24.1"
strum_macros = "0.24"