[package]
name = "netcup-offer-bot"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.51", features = ["backtrace"] }
thiserror = "1.0"
sentry = { version = "0.29.3", features = ["anyhow", "debug-images", "log", "reqwest"] }
log = "0.4.17"
fern = "0.6.1"
chrono = { version = "0.4.23", features = ["serde"] }
webhook = "2.1.2"
rss = { version = "2.0.0", features = ["validation"] }
reqwest = { version = "0.11" }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.11"
strum = "0.24.1"
strum_macros = "0.24"
serde = "1.0.152"
serde_json = "1.0.93"
prometheus = { version = "0.13", features = ["process"] }
prometheus_exporter = "0.8.5"
lazy_static = "1.4.0"

[profile.release]
lto = true
codegen-units = 1