[package]
name = "netcup-offer-bot"
version = "1.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "netcup-offer-bot"

[dependencies]
anyhow = { version = "1.0.51", features = ["backtrace"] }
thiserror = "1.0"
backtrace = "0.3.67"
sentry = { version = "0.30.0", features = ["anyhow", "debug-images", "reqwest", "backtrace", "tracing", "profiling"] }
chrono = { version = "0.4.23", default-features = false, features = ["clock", "std", "wasmbind", "serde"] }
webhook = "2.1.2"
rss = { version = "2.0.0", features = ["validation"] }
reqwest = { version = "0.11.14" }
reqwest-middleware = "0.2.0"
reqwest-tracing = "0.4.0"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.11"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
strum = "0.24.1"
strum_macros = "0.24"
serde = "1.0.152"
serde_json = "1.0.93"
lazy_static = "1.4.0"
secrecy = { version = "0.8.0", features = ["serde"] }
config = "0.13.3"
opentelemetry = { version = "0.18.0", features = ["rt-tokio", "rt-tokio-current-thread"] }
opentelemetry-prometheus = "0.11.0"
actix-web-opentelemetry = { version = "0.13.0", features = ["metrics", "metrics-prometheus"] }
actix-web = "4.3.1"

[dev-dependencies]
temp-env = "0.3.1"
tempfile = "3.3.0"
serde_test = "1.0.152"

[profile.release]
lto = true
codegen-units = 1
debug = true