apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
{{ include "common.labels" . | indent 4 }}
  name: {{ .Release.Name }}-claim
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
