apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels: 
{{ include "common.labels" . | indent 4 }}
data:
  sentryDns: {{ required "sentryDns is required" .Values.env.sentryDns | b64enc }}
  webHook: {{ required "webHook is required" .Values.env.webHook | b64enc }}